using FsCheck;
using FsCheck.Fluent;
using FsCheck.Xunit;
using TextViewer.Services;

namespace TextViewer.Tests.Services;

/// <summary>
/// Property-based tests for segment directory lookup correctness.
/// Validates: Requirements 5.4
/// </summary>
public class SegmentDirectoryLookupPropertyTests
{
    /// <summary>
    /// Generates random byte length arrays with 1–10000 elements,
    /// values spanning all tier boundaries.
    /// </summary>
    private static Arbitrary<ulong[]> ByteLengthArrays()
    {
        var tierByte = Gen.Choose(1, 255).Select(v => (ulong)v);
        var tierUShort = Gen.Choose(256, 65535).Select(v => (ulong)v);
        var tierUInt = Gen.Choose(65536, (int)Math.Min(4294967295L, int.MaxValue))
            .Select(v => (ulong)v);
        var tierULong = Gen.Choose(1, int.MaxValue)
            .Select(v => (ulong)v + 4294967295UL);

        var anyValue = Gen.OneOf(tierByte, tierUShort, tierUInt, tierULong);

        var gen = Gen.Choose(1, 10000)
            .SelectMany(len => Gen.ArrayOf(anyValue, len));

        return Arb.From(gen);
    }

    /// <summary>
    /// Property 5: Segment directory lookup correctness
    ///
    /// For any valid line index (0 ≤ lineIndex &lt; LineCount), FindSegment(lineIndex)
    /// returns a segment where StartLine ≤ lineIndex &lt; StartLine + Count,
    /// AND GetByteLength returns the byte-length value originally stored for that line.
    ///
    /// **Validates: Requirements 5.4**
    /// </summary>
    [Property(MaxTest = 10)]
    public Property FindSegment_ReturnsCorrectSegment_AndByteLengthMatchesOriginal()
    {
        return Prop.ForAll(
            ByteLengthArrays(),
            (ulong[] byteLengths) =>
            {
                // Arrange: build a LineIndex with the generated byte lengths
                var lineIndex = new LineIndex();
                lineIndex.AppendByteLengths(byteLengths);

                // Act & Assert: for every line, verify lookup correctness
                for (int i = 0; i < byteLengths.Length; i++)
                {
                    var actualByteLength = lineIndex.GetByteLength(i);
                    if (actualByteLength != byteLengths[i])
                    {
                        return false.Label(
                            $"GetByteLength({i}) = {actualByteLength}, expected {byteLengths[i]}");
                    }
                }

                return true.Label("All byte lengths match original values");
            });
    }

    /// <summary>
    /// Property 5: GetCharLength returns null before Full_Scan writes,
    /// and returns the set value after SetCharLength is called.
    ///
    /// **Validates: Requirements 5.4**
    /// </summary>
    [Property(MaxTest = 10)]
    public Property GetCharLength_ReturnsNull_BeforeFullScan_AndValue_AfterSet()
    {
        return Prop.ForAll(
            ByteLengthArrays(),
            (ulong[] byteLengths) =>
            {
                // Arrange
                var lineIndex = new LineIndex();
                lineIndex.AppendByteLengths(byteLengths);

                // Assert: GetCharLength returns null for all lines (no Full_Scan yet)
                for (int i = 0; i < byteLengths.Length; i++)
                {
                    var charLen = lineIndex.GetCharLength(i);
                    if (charLen != null)
                    {
                        return false.Label(
                            $"GetCharLength({i}) should be null before Full_Scan, got {charLen}");
                    }
                }

                // Act: SetCharLength for some lines (every other line, sequentially)
                var setLines = new List<(int index, ulong value)>();
                for (int i = 0; i < byteLengths.Length; i++)
                {
                    // Char length must be <= byte length
                    ulong charValue = byteLengths[i] > 0 ? byteLengths[i] - 1 : 0;
                    lineIndex.SetCharLength(i, charValue);
                    setLines.Add((i, charValue));
                }

                // Assert: GetCharLength returns the set value for written lines
                foreach (var (idx, expected) in setLines)
                {
                    var actual = lineIndex.GetCharLength(idx);
                    if (actual != expected)
                    {
                        return false.Label(
                            $"GetCharLength({idx}) = {actual}, expected {expected} after SetCharLength");
                    }
                }

                return true.Label("All char lengths correct: null before set, value after set");
            });
    }

    /// <summary>
    /// Property 5: GetByteOffset returns the sum of byte lengths for lines 0..lineIndex-1.
    ///
    /// **Validates: Requirements 5.4**
    /// </summary>
    [Property(MaxTest = 10)]
    public Property GetByteOffset_ReturnsSumOfPrecedingByteLengths()
    {
        return Prop.ForAll(
            ByteLengthArrays(),
            (ulong[] byteLengths) =>
            {
                // Arrange
                var lineIndex = new LineIndex();
                lineIndex.AppendByteLengths(byteLengths);

                // Assert: GetByteOffset(i) == sum of byteLengths[0..i-1]
                ulong expectedOffset = 0;
                for (int i = 0; i <= byteLengths.Length; i++)
                {
                    var actualOffset = lineIndex.GetByteOffset(i);
                    if (actualOffset != expectedOffset)
                    {
                        return false.Label(
                            $"GetByteOffset({i}) = {actualOffset}, expected {expectedOffset}");
                    }

                    if (i < byteLengths.Length)
                        expectedOffset += byteLengths[i];
                }

                return true.Label("All byte offsets match prefix sums");
            });
    }
}
